"""add graph tables

Revision ID: 55c31769c428
Revises: 521ead423060
Create Date: 2026-07-16 19:33:19.822734
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '55c31769c428'
down_revision: Union[str, None] = '521ead423060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('embedding_vector', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_nodes_document_version_id'), 'graph_nodes', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_graph_nodes_organization_id'), 'graph_nodes', ['organization_id'], unique=False)
    op.create_table('graph_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('source_module', sa.String(length=50), nullable=False),
    sa.Column('extraction_algorithm', sa.String(length=50), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_node_id'], ['graph_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['graph_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_edges_document_version_id'), 'graph_edges', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_organization_id'), 'graph_edges', ['organization_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_source_node_id'), 'graph_edges', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_target_node_id'), 'graph_edges', ['target_node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graph_edges_target_node_id'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_source_node_id'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_organization_id'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_document_version_id'), table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_index(op.f('ix_graph_nodes_organization_id'), table_name='graph_nodes')
    op.drop_index(op.f('ix_graph_nodes_document_version_id'), table_name='graph_nodes')
    op.drop_table('graph_nodes')
    # ### end Alembic commands ###
