"""add agent registry tables

Revision ID: 7cc1f197c4f6
Revises: 55c31769c428
Create Date: 2026-07-16 19:47:02.816240
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '7cc1f197c4f6'
down_revision: Union[str, None] = '55c31769c428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_metrics_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('total_latency_ms', sa.Integer(), nullable=False),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cpu_usage_pct', sa.Float(), nullable=False),
    sa.Column('memory_usage_mb', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'version', name='uq_agent_metric_version')
    )
    op.create_index(op.f('ix_agent_metrics_log_agent_id'), 'agent_metrics_log', ['agent_id'], unique=False)
    op.create_table('agent_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('supported_tasks', sa.JSON(), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=False),
    sa.Column('output_schema', sa.JSON(), nullable=False),
    sa.Column('policy', sa.JSON(), nullable=False),
    sa.Column('health_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'version', name='uq_agent_version')
    )
    op.create_index(op.f('ix_agent_registry_agent_id'), 'agent_registry', ['agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_registry_agent_id'), table_name='agent_registry')
    op.drop_table('agent_registry')
    op.drop_index(op.f('ix_agent_metrics_log_agent_id'), table_name='agent_metrics_log')
    op.drop_table('agent_metrics_log')
    # ### end Alembic commands ###
