"""Add quality and prompt tables

Revision ID: 8ba09f57eabd
Revises: 
Create Date: 2026-07-12 00:12:39.731597
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '8ba09f57eabd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmark_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('expected_answer', sa.Text(), nullable=False),
    sa.Column('expected_citations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmark_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('kb_version', sa.String(length=50), nullable=False),
    sa.Column('embedding_version', sa.String(length=50), nullable=False),
    sa.Column('retrieval_metrics', sa.JSON(), nullable=False),
    sa.Column('citation_metrics', sa.JSON(), nullable=False),
    sa.Column('latency', sa.Float(), nullable=False),
    sa.Column('confidence_calibration', sa.JSON(), nullable=False),
    sa.Column('regression_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('associated_model', sa.String(length=255), nullable=False),
    sa.Column('kb_version', sa.String(length=50), nullable=False),
    sa.Column('performance_metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt_registry')
    op.drop_table('benchmark_runs')
    op.drop_table('benchmark_questions')
    # ### end Alembic commands ###
